# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Passwords.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from func import resource_path


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 800))
        MainWindow.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 5px; \n"
"    margin-top: 20px; \n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px; \n"
"    background: #ccc; \n"
"    border: 1px solid #ccc; \n"
"    border-radius: 5px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    spacing: 5px; \n"
"    background: #ffffff;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px; \n"
"    height: 20px; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 2px solid #666; \n"
"    background-color: #fff; \n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #007acc;\n"
"    background-color: #007acc;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    border: 2px solid #007acc;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    border: 2px solid #004477;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: lightgray; \n"
"    border: 1px solid #999; \n"
"    height: 8px; \n"
"    margin: 2px 0; \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #eee, stop:1 #ccc);\n"
"    border: 1px solid #777;\n"
"    width: 15px; \n"
"    margin: -8px 0; \n"
"    border-radius: 3px; \n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #ccc; \n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #66a, stop:1 #55c);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1100, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("copacity:0%")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.save_passwords_tab = QtWidgets.QWidget()
        self.save_passwords_tab.setObjectName("save_passwords_tab")
        self.img_save_tab = QtWidgets.QLabel(self.save_passwords_tab)
        self.img_save_tab.setGeometry(QtCore.QRect(0, 0, 1100, 800))
        self.img_save_tab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_save_tab.setText("")
        self.img_save_tab.setTextFormat(QtCore.Qt.AutoText)
        self.img_save_tab.setPixmap(QtGui.QPixmap(resource_path("img/new.jpg")))
        self.img_save_tab.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.img_save_tab.setObjectName("img_save_tab")
        self.edit_fields_box = QtWidgets.QGroupBox(self.save_passwords_tab)
        self.edit_fields_box.setGeometry(QtCore.QRect(40, 170, 491, 271))
        self.edit_fields_box.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}")
        self.edit_fields_box.setTitle("")
        self.edit_fields_box.setObjectName("edit_fields_box")
        self.gridLayout = QtWidgets.QGridLayout(self.edit_fields_box)
        self.gridLayout.setObjectName("gridLayout")
        self.password_edt = QtWidgets.QLineEdit(self.edit_fields_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_edt.sizePolicy().hasHeightForWidth())
        self.password_edt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.password_edt.setFont(font)
        self.password_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password_edt.setStyleSheet("")
        self.password_edt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edt.setCursorPosition(0)
        self.password_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.password_edt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password_edt.setObjectName("password_edt")
        self.gridLayout.addWidget(self.password_edt, 4, 0, 1, 1)
        self.description_edt = QtWidgets.QLineEdit(self.edit_fields_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_edt.sizePolicy().hasHeightForWidth())
        self.description_edt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.description_edt.setFont(font)
        self.description_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.description_edt.setStyleSheet("")
        self.description_edt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.description_edt.setCursorPosition(0)
        self.description_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.description_edt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.description_edt.setObjectName("description_edt")
        self.gridLayout.addWidget(self.description_edt, 1, 0, 1, 1)
        self.pass_show_btn = QtWidgets.QPushButton(self.edit_fields_box)
        self.pass_show_btn.setMinimumSize(QtCore.QSize(42, 42))
        self.pass_show_btn.setStyleSheet("")
        self.pass_show_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("img/eye_hide.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pass_show_btn.setIcon(icon)
        self.pass_show_btn.setObjectName("pass_show_btn")
        self.gridLayout.addWidget(self.pass_show_btn, 4, 1, 1, 1)
        self.login_edt = QtWidgets.QLineEdit(self.edit_fields_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_edt.sizePolicy().hasHeightForWidth())
        self.login_edt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.login_edt.setFont(font)
        self.login_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login_edt.setStyleSheet("")
        self.login_edt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login_edt.setCursorPosition(0)
        self.login_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.login_edt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.login_edt.setObjectName("login_edt")
        self.gridLayout.addWidget(self.login_edt, 0, 0, 1, 1)
        self.show_passwords_tedt = QtWidgets.QTextEdit(self.save_passwords_tab)
        self.show_passwords_tedt.setGeometry(QtCore.QRect(560, 40, 481, 581))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        self.show_passwords_tedt.setFont(font)
        self.show_passwords_tedt.setStyleSheet("")
        self.show_passwords_tedt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.show_passwords_tedt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.show_passwords_tedt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.show_passwords_tedt.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.show_passwords_tedt.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.show_passwords_tedt.setObjectName("show_passwords_tedt")
        self.background_show_pass_lbl = QtWidgets.QLabel(self.save_passwords_tab)
        self.background_show_pass_lbl.setGeometry(QtCore.QRect(549, 39, 501, 591))
        self.background_show_pass_lbl.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ccc;\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"")
        self.background_show_pass_lbl.setText("")
        self.background_show_pass_lbl.setObjectName("background_show_pass_lbl")
        self.key_edt = QtWidgets.QLineEdit(self.save_passwords_tab)
        self.key_edt.setGeometry(QtCore.QRect(40, 670, 461, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_edt.sizePolicy().hasHeightForWidth())
        self.key_edt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.key_edt.setFont(font)
        self.key_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.key_edt.setStyleSheet("")
        self.key_edt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.key_edt.setCursorPosition(0)
        self.key_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.key_edt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.key_edt.setObjectName("key_edt")
        self.save_to_img = QtWidgets.QPushButton(self.save_passwords_tab)
        self.save_to_img.setGeometry(QtCore.QRect(710, 670, 201, 42))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        self.save_to_img.setFont(font)
        self.save_to_img.setObjectName("save_to_img")
        self.add_to_list_btn = QtWidgets.QPushButton(self.save_passwords_tab)
        self.add_to_list_btn.setGeometry(QtCore.QRect(150, 460, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        self.add_to_list_btn.setFont(font)
        self.add_to_list_btn.setStyleSheet("")
        self.add_to_list_btn.setObjectName("add_to_list_btn")
        self.img_save_tab.raise_()
        self.edit_fields_box.raise_()
        self.background_show_pass_lbl.raise_()
        self.show_passwords_tedt.raise_()
        self.key_edt.raise_()
        self.save_to_img.raise_()
        self.add_to_list_btn.raise_()
        self.tabWidget.addTab(self.save_passwords_tab, "")
        self.generate_password_tab = QtWidgets.QWidget()
        self.generate_password_tab.setObjectName("generate_password_tab")
        self.img_generate_tab = QtWidgets.QLabel(self.generate_password_tab)
        self.img_generate_tab.setGeometry(QtCore.QRect(0, 0, 1100, 800))
        self.img_generate_tab.setText("")
        self.img_generate_tab.setPixmap(QtGui.QPixmap(resource_path("img/new.jpg")))
        self.img_generate_tab.setAlignment(QtCore.Qt.AlignCenter)
        self.img_generate_tab.setObjectName("img_generate_tab")
        self.generate_key_gbx = QtWidgets.QGroupBox(self.generate_password_tab)
        self.generate_key_gbx.setGeometry(QtCore.QRect(50, 470, 1011, 151))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(12)
        self.generate_key_gbx.setFont(font)
        self.generate_key_gbx.setStyleSheet("")
        self.generate_key_gbx.setObjectName("generate_key_gbx")
        self.key_generate_btn = QtWidgets.QPushButton(self.generate_key_gbx)
        self.key_generate_btn.setGeometry(QtCore.QRect(90, 70, 201, 42))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        self.key_generate_btn.setFont(font)
        self.key_generate_btn.setObjectName("key_generate_btn")
        self.key_generate_edt = QtWidgets.QLineEdit(self.generate_key_gbx)
        self.key_generate_edt.setGeometry(QtCore.QRect(330, 70, 571, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_generate_edt.sizePolicy().hasHeightForWidth())
        self.key_generate_edt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.key_generate_edt.setFont(font)
        self.key_generate_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.key_generate_edt.setStyleSheet("")
        self.key_generate_edt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.key_generate_edt.setCursorPosition(0)
        self.key_generate_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.key_generate_edt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.key_generate_edt.setObjectName("key_generate_edt")
        self.generate_pass_gbx = QtWidgets.QGroupBox(self.generate_password_tab)
        self.generate_pass_gbx.setGeometry(QtCore.QRect(50, 40, 1011, 351))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(12)
        self.generate_pass_gbx.setFont(font)
        self.generate_pass_gbx.setStyleSheet("")
        self.generate_pass_gbx.setObjectName("generate_pass_gbx")
        self.digits_cbx = QtWidgets.QCheckBox(self.generate_pass_gbx)
        self.digits_cbx.setGeometry(QtCore.QRect(300, 250, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(12)
        self.digits_cbx.setFont(font)
        self.digits_cbx.setStyleSheet("")
        self.digits_cbx.setChecked(True)
        self.digits_cbx.setObjectName("digits_cbx")
        self.lower_cbx = QtWidgets.QCheckBox(self.generate_pass_gbx)
        self.lower_cbx.setGeometry(QtCore.QRect(420, 250, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(12)
        self.lower_cbx.setFont(font)
        self.lower_cbx.setStyleSheet("")
        self.lower_cbx.setChecked(True)
        self.lower_cbx.setObjectName("lower_cbx")
        self.generate_password_edt = QtWidgets.QLineEdit(self.generate_pass_gbx)
        self.generate_password_edt.setGeometry(QtCore.QRect(80, 90, 571, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_password_edt.sizePolicy().hasHeightForWidth())
        self.generate_password_edt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.generate_password_edt.setFont(font)
        self.generate_password_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.generate_password_edt.setStyleSheet("")
        self.generate_password_edt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.generate_password_edt.setCursorPosition(0)
        self.generate_password_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.generate_password_edt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.generate_password_edt.setObjectName("generate_password_edt")
        self.len_pass_edt = QtWidgets.QLineEdit(self.generate_pass_gbx)
        self.len_pass_edt.setGeometry(QtCore.QRect(810, 180, 81, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.len_pass_edt.sizePolicy().hasHeightForWidth())
        self.len_pass_edt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.len_pass_edt.setFont(font)
        self.len_pass_edt.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.len_pass_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.len_pass_edt.setStyleSheet("")
        self.len_pass_edt.setInputMask("")
        self.len_pass_edt.setMaxLength(2)
        self.len_pass_edt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.len_pass_edt.setCursorPosition(2)
        self.len_pass_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.len_pass_edt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.len_pass_edt.setObjectName("len_pass_edt")
        self.len_pass_slider = QtWidgets.QSlider(self.generate_pass_gbx)
        self.len_pass_slider.setGeometry(QtCore.QRect(80, 180, 721, 41))
        self.len_pass_slider.setStyleSheet("")
        self.len_pass_slider.setPageStep(1)
        self.len_pass_slider.setProperty("value", 10)
        self.len_pass_slider.setOrientation(QtCore.Qt.Horizontal)
        self.len_pass_slider.setObjectName("len_pass_slider")
        self.symbol_cbx = QtWidgets.QCheckBox(self.generate_pass_gbx)
        self.symbol_cbx.setGeometry(QtCore.QRect(660, 250, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(12)
        self.symbol_cbx.setFont(font)
        self.symbol_cbx.setStyleSheet("")
        self.symbol_cbx.setChecked(False)
        self.symbol_cbx.setObjectName("symbol_cbx")
        self.generate_password_btn = QtWidgets.QPushButton(self.generate_pass_gbx)
        self.generate_password_btn.setGeometry(QtCore.QRect(690, 90, 201, 42))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        self.generate_password_btn.setFont(font)
        self.generate_password_btn.setObjectName("generate_password_btn")
        self.upper_cbx = QtWidgets.QCheckBox(self.generate_pass_gbx)
        self.upper_cbx.setGeometry(QtCore.QRect(540, 250, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(12)
        self.upper_cbx.setFont(font)
        self.upper_cbx.setStyleSheet("")
        self.upper_cbx.setChecked(True)
        self.upper_cbx.setObjectName("upper_cbx")
        self.tabWidget.addTab(self.generate_password_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Passwords"))
        self.password_edt.setPlaceholderText(_translate("MainWindow", "Password"))
        self.description_edt.setPlaceholderText(_translate("MainWindow", "Description"))
        self.login_edt.setPlaceholderText(_translate("MainWindow", "Login"))
        self.key_edt.setPlaceholderText(_translate("MainWindow", "Key"))
        self.save_to_img.setText(_translate("MainWindow", "Сохранить"))
        self.add_to_list_btn.setText(_translate("MainWindow", "Добавить в список"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.save_passwords_tab), _translate("MainWindow", "Save Passwords"))
        self.generate_key_gbx.setTitle(_translate("MainWindow", "Generate Key"))
        self.key_generate_btn.setText(_translate("MainWindow", "Создать ключ"))
        self.key_generate_edt.setPlaceholderText(_translate("MainWindow", "Key"))
        self.generate_pass_gbx.setTitle(_translate("MainWindow", "Password Generation"))
        self.digits_cbx.setText(_translate("MainWindow", "0 - 9"))
        self.lower_cbx.setText(_translate("MainWindow", "a - z"))
        self.generate_password_edt.setPlaceholderText(_translate("MainWindow", "Password"))
        self.len_pass_edt.setText(_translate("MainWindow", "10"))
        self.len_pass_edt.setPlaceholderText(_translate("MainWindow", "0"))
        self.symbol_cbx.setText(_translate("MainWindow", "@#$%"))
        self.generate_password_btn.setText(_translate("MainWindow", "Сгенерировать пароль"))
        self.upper_cbx.setText(_translate("MainWindow", "A - Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generate_password_tab), _translate("MainWindow", "Generate Password"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
